# Generated by Django 5.1.6 on 2025-03-11 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMO_board', '0002_post_text_alter_response_date_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(default=0),
        ),
    ]
